# Railway deployment configuration
# This file tells Railway how to deploy the application

# Python version
python-version: 3.11

# Build command (if needed)
build: pip install -r requirements.txt

# Start command
start: python app.py

# Environment variables (set these in Railway dashboard)
# BRAVE_SEARCH_API_KEY=your_brave_api_key_here
# ANTHROPIC_API_KEY=your_anthropic_api_key_here
