# Railway deployment configuration
# This file tells Railway how to deploy the application

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app.py"

# Railway will auto-detect Python and install dependencies
# Node.js will be installed via package.json
