# Railway deployment configuration
# This file tells Railway how to deploy the application

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "sh -c 'if [ \"$RAILWAY_CRON_SCHEDULE\" ]; then python -c \"from app import run_cron_generation; import sys; sys.exit(0 if run_cron_generation() else 1)\"; else gunicorn -w 2 -k gthread --threads 4 -t 180 app:app --bind 0.0.0.0:${PORT:-8080}; fi'"

# Cron schedule configuration
[cron]
schedule = "0 */5 * * *"  # Every 5 hours
command = "python cron.py"

# Railway will use the Dockerfile for building
# Both Python and Node.js will be properly set up