# Railway deployment configuration
# This file tells Railway how to deploy the application

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app.py"

# Environment variables (set these in Railway dashboard)
# BRAVE_SEARCH_API_KEY=your_brave_api_key_here
# ANTHROPIC_API_KEY=your_anthropic_api_key_here
